version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

commands:
  test_core:
    parameters:
      py:
        default: "310"
        type: string
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install -r ./test_requirements/requirements_<<parameters.py>>_core.txt
      - run:
          name: Test core
          command: |
            . venv/bin/activate
            pytest tests/test_core
          no_output_timeout: 20m

  test_optional:
    parameters:
      py:
        default: "310"
        type: string
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv venv
            source .venv/bin/activate
            uv pip install .
            uv pip install -r ./test_requirements/requirements_<<parameters.py>>_optional.txt
            cd js
            npm ci
            npm run build
      - run:
          name: Install plotly-geo
          command: |
            source .venv/bin/activate
            uv pip install plotly-geo
      - run:
          name: Test core
          command: |
            source .venv/bin/activate
            pytest tests/test_core
          no_output_timeout: 20m
      - run:
          name: Test optional
          command: |
            source .venv/bin/activate
            pytest tests/test_optional
          no_output_timeout: 40m
      - run:
          name: Test utils
          command: |
            source .venv/bin/activate
            pytest tests/test_plotly_utils/
          no_output_timeout: 20m
      - run:
          name: Test io
          command: |
            source .venv/bin/activate
            python -m pytest tests/test_io
          no_output_timeout: 20m
      - run:
          name: Test dependencies not imported
          command: |
            source .venv/bin/activate
            python -m pytest -x test_init/test_dependencies_not_imported.py
      - run:
          name: Test lazy imports
          command: |
            source .venv/bin/activate
            python -m pytest -x test_init/test_lazy_imports.py
  test_orca:
    parameters:
      py:
        default: "310"
        type: string
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r ./test_requirements/requirements_<<parameters.py>>_optional.txt
      - run:
          name: Install plotly-geo
          command: |
            . venv/bin/activate
            pip install plotly-geo
      - run:
          name: Install orca
          command: |
            npm install electron@1.8.4
            npm install orca
            sudo apt-get update
            sudo apt-get install -y poppler-utils libxtst6 xvfb libgtk2.0-0 libgconf-2-4 libnss3 libasound2 rename
            echo 'export PATH="/home/circleci/project/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run:
          name: Test orca
          command: |
            . venv/bin/activate
            pytest tests/test_orca
          no_output_timeout: 20m
      - store_artifacts:
          path: tests/test_orca/images/linux/failed

jobs:
  check-code-formatting:
    docker:
      - image: cimg/python:3.7

    steps:
      - checkout
      - run:
          name: Install black
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install black==22.3.0
      - run:
          name: Check formatting with black
          command: |
            . venv/bin/activate
            black --check . --exclude venv

  # Core
  python_38_core:
    docker:
      - image: cimg/python:3.8-browsers
    steps:
      - test_core:
          py: "38"

  python_39_core:
    docker:
      - image: cimg/python:3.9-browsers
    steps:
      - test_core:
          py: "39"

  python_310_core:
    docker:
      - image: cimg/python:3.10-browsers
    steps:
      - test_core:
          py: "310"

  python_311_core:
    docker:
      - image: cimg/python:3.11-browsers
    steps:
      - test_core:
          py: "311"

  python_312_core:
    docker:
      - image: cimg/python:3.12-browsers
    steps:
      - test_core:
          py: "312"

  # Optional

  python_38_optional:
    docker:
      - image: cimg/python:3.8-browsers
    steps:
      - test_optional:
          py: "38"

  python_39_optional:
    docker:
      - image: cimg/python:3.9-browsers
    steps:
      - test_optional:
          py: "39"

  python_310_optional:
    docker:
      - image: cimg/python:3.10-browsers
    steps:
      - test_optional:
          py: "310"

  python_311_optional:
    docker:
      - image: cimg/python:3.11-browsers
    steps:
      - test_optional:
          py: "311"

  python_312_optional:
    docker:
      - image: cimg/python:3.12-browsers
    steps:
      - test_optional:
          py: "312"

  # Pandas

  python_39_pandas_2_optional:
    docker:
      - image: cimg/python:3.9-browsers
    steps:
      - test_optional:
          py: "39_pandas_2"

  # No numpy
  python_312_no_numpy:
    docker:
      - image: cimg/python:3.12-browsers
    steps:
      - run:
          name: Check that numpy is not installed
          command: |
            if pip list | grep numpy > /dev/null 2>&1
            then exit 1
            else exit 0
            fi
      - test_optional:
          py: "312_no_numpy"

  python_312_np2:
    docker:
      - image: cimg/python:3.12-browsers
    steps:
      - test_optional:
          py: "312_np2"


  # Percy
  python_39_percy:
    docker:
      - image: cimg/python:3.9-browsers
        environment:
          PERCY_ENABLED: True
          PERCY_PROJECT: plotly/plotly.py
    resource_class: large

    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Inject Percy Environment variables
          command: |
            echo 'export PERCY_TOKEN="$PERCY_PYTHON_TOKEN_V0"' >> $BASH_ENV
      - run:
          name: Install requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install plotly-geo
            pip install -r test_requirements/requirements_39_pandas_2_optional.txt

      - run:
          name: Build html figures (Pandas 2)
          command: |
            . venv/bin/activate
            python tests/percy/plotly-express.py
      - run:
          name: Build html figures (Pandas 1) and compare
          command: |
            . venv/bin/activate
            mkdir tests/percy/pandas2
            mv tests/percy/*.html tests/percy/pandas2/
            # 1.1 is the earliest minor with Py3.9 wheels
            pip install "pandas==1.1.5"
            python tests/percy/plotly-express.py
            python tests/percy/compare-pandas.py
            rm -rf tests/percy/pandas2
      - run:
          name: Run percy snapshots
          command: |
            npm i @percy/cli
            npx percy snapshot -c tests/percy/snapshots.yml tests/percy/
            rm tests/percy/*.html

  plotlyjs_dev_build:
    docker:
      - image: cimg/python:3.11-node
        environment:
          LANG: en_US.UTF-8
    resource_class: large

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install -r ./test_requirements/requirements_311_core.txt black inflect
            pip install jupyterlab
      - run:
          name: Update plotly.js to dev
          command: |
            . venv/bin/activate
            python commands.py updateplotlyjsdev
      - run:
          name: Test core
          command: |
            . venv/bin/activate
            locale
            pytest -k 'not nodev' tests/test_core
          no_output_timeout: 20m
      - run:
          name: Commit
          command: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git add -A
            git commit -m "Codegen"
          when: always
      - run:
          name: Build source distribution packages
          command: |
            . venv/bin/activate
            pip install build
            python -m build --sdist --wheel -o dist
          when: always
      - store_artifacts:
          path: dist/

  full_build:
    docker:
      - image: cimg/python:3.11-node
        environment:
          LANG: en_US.UTF-8
    resource_class: large

    steps:
      - checkout

      - run:
          name: initial NPM Build
          command: |
            python -m venv venv
            . venv/bin/activate
            cd js
            npm ci
            npm run build
            git status

      - run:
          name: PyPI Build
          command: |
            . venv/bin/activate
            pip install build
            python -m build --sdist --wheel -o dist
            cp -R dist output
            git status

      - run:
          name: Zip output
          command: |
            tar czf output.tgz output

      - store_artifacts:
          path: output.tgz

  build-doc:
    resource_class: xlarge
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, for example, `3.9-browsers`
      - image: cimg/python:3.9-browsers

    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:5f:39:48:00:b4:72:34:e1:d2:c4:e1:1f:d1:e2:ce" #plotlydocbot

      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: install dependencies
          command: |
            cd doc
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv venv
            source .venv/bin/activate
            uv pip uninstall -y plotly
            uv pip install -r requirements.txt
            if [ "${CIRCLE_BRANCH}" != "doc-prod" ]; then
              uv pip uninstall -y plotly
              cd ..
              uv pip install -e .
              cd js
              npm ci
              npm run build
              cd ../doc
            fi
            cd ..
      - run:
          name: Install orca
          command: |
            npm install electron@1.8.4
            npm install orca
            sudo apt-get update
            sudo apt-get install -y poppler-utils libxtst6 xvfb libgtk2.0-0 libgconf-2-4 libnss3 libasound2 rename
            echo 'export PATH="/home/circleci/project/node_modules/.bin:$PATH"' >> $BASH_ENV

      - run:
          name: make html
          command: |
            cd doc
            source .venv/bin/activate
            echo ${mapbox_token} > python/.mapbox_token
            make -kj8 || make -kj8
            curl https://raw.githubusercontent.com/plotly/graphing-library-docs/master/front-matter-ci.py > front-matter-ci.py
            curl https://raw.githubusercontent.com/plotly/graphing-library-docs/master/check-or-enforce-order.py > check-or-enforce-order.py
            python front-matter-ci.py build/html
            python check-or-enforce-order.py build/html
            if [ "${CIRCLE_BRANCH}" == "doc-prod" ]; then
              cd build/html
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git add *
              git commit -m "build of https://github.com/plotly/plotly.py/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotly.py-docs.git master:built
              rm -rf .git
              cd ../..
              cd build/ipynb
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git add *
              git commit -m "build of https://github.com/plotly/plotly.py/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotly.py-docs.git master:built_ipynb
              rm -rf .git
              cd ../..
            fi
            tar -zcf build/html.tgz build/html
            rm -rf build/html build/ipynb
            cd ..

      - run:
          name: trigger doc build
          command: |
            if [ "${CIRCLE_BRANCH}" == "doc-prod" ]; then
              git clone --depth=1 https://github.com/plotly/graphing-library-docs.git
              cd graphing-library-docs
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git commit --allow-empty -m "deploying https://github.com/plotly/plotly.py/commit/${CIRCLE_SHA1}"
              git push
              cd ..
              rm -rf graphing-library-docs
            fi

      - run:
          name: make doc
          command: |
            cd doc
            source .venv/bin/activate
            # For the API doc, we need to use the local version of plotly
            # since we are tweaking the source because of
            # graph_objs/graph_objects
            if [ "${CIRCLE_BRANCH}" == "doc-prod" ]; then
              uv pip uninstall plotly
              cd ..
              uv pip install -e .
              cd doc
              cd apidoc
              make html
              cd _build/html
              touch .nojekyll
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              git add *
              git add .nojekyll
              git commit -m "build of https://github.com/plotly/plotly.py/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotly.py-docs.git master:gh-pages
              rm -rf .git
              cd ../..
            fi

      - store_artifacts:
          path: doc/build
          destination: doc/build
workflows:
  code_formatting:
    jobs:
      - check-code-formatting
  dev_build:
    jobs:
      - plotlyjs_dev_build
  release_build:
    jobs:
      - full_build

  build:
    jobs:
      - python_38_core
      - python_39_core
      - python_310_core
      - python_311_core
      - python_312_core
      - python_38_optional
      - python_39_optional
      - python_310_optional
      - python_311_optional
      - python_312_optional
      - python_39_pandas_2_optional
      - python_39_percy
      - python_312_no_numpy
      - python_312_np2
      - build-doc
